version: '3'
services:
  app:
    build: .
    container_name: telegram-bot-youtube-download
    volumes:
      - .:/app/
      - /app/node_modules
    depends_on:
      - telegram-api
    command: npm start
  telegram-api:
    image: ghcr.io/lukaszraczylo/tdlib-telegram-bot-api-docker/telegram-api-server:latest
    container_name: telegram-api-youtube-download
    env_file: .env 